MODEL:
  NAME: 'patchconvnet_s60_224_21k'
  BACKBONE_EMB_SIZE: 384
  PRETRAIN_PATH: 'models/s60_224_21k.pth'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.003
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 30
  EVAL_PERIOD: 5

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1