MODEL:
  NAME: 'patchconvnet_s60_384_21k'
  BACKBONE_EMB_SIZE: 1536
  PRETRAIN_PATH: 'models/s60_224_21k.pth'
  KEEP_CAMID_CENTROIDS: True
  RESUME_TRAINING: True

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 3

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1