MODEL:
  NAME: 'cait_XXS36_224'
  BACKBONE_EMB_SIZE: 1024
  PRETRAIN_PATH: 'models\XXS36_224.pth'
  KEEP_CAMID_CENTROIDS: True
  PRETRAINED: False

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 3
  CHECKPOINT_PERIOD: 3
  LR_STEPS : [12, 60]

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1