MODEL:
  NAME: 'deit_small_224_21k'
  BACKBONE_EMB_SIZE: 1536
  PRETRAIN_PATH: "./models/deit_3_small_224_21k.pth" # load from url
  KEEP_CAMID_CENTROIDS: True
  PRETRAINED: True
  

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.00002
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 200
  CHECKPOINT_PERIOD: 3
  WEIGHT_DECAY: 0.02
  EVAL_PERIOD: 3
  LR_SCHEDULER_NAME: "multistep_lr"
  LR_STEPS: [15, 30]
  MIN_LR: 0.000001

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1