MODEL:
  NAME: 'cait_XS24'
  BACKBONE_EMB_SIZE: 1024
  PRETRAIN_PATH: 'models\XS24_384.pth'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.001
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 120
  CHECKPOINT_PERIOD: 3
  EVAL_PERIOD: 3
  LR_STEPS : [30, 60]

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1