MODEL:
  NAME: 'resnet50_ibn_a'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: 'models/centroids_df_resnet_50_ibn_a_checkpoint_119.pth'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [320,320]
  SIZE_TEST: [320,320]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 40

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1